# Generated by Django 4.2 on 2023-04-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='users/profile', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank='True', verbose_name='Introduction'),
        ),
    ]
